name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run Flake8 Linter
      run: |
        echo "Running Flake8 linter..."
        flake8 calculator.py test_calculator.py --max-line-length=88 --extend-ignore=E203
    
    - name: Run Tests
      if: success()
      run: |
        echo "Running pytest..."
        pytest test_calculator.py -v --tb=short